name: Code Quality Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Check required files exist
      run: |
        echo "Checking for required source files..."
        required_files=(
          "cpu8085.h"
          "cpu8085.cpp"
          "gui.cpp"
          "Makefile"
          "CMakeLists.txt"
          "README.md"
          "LICENSE"
        )
        
        missing_files=()
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            missing_files+=("$file")
            echo "❌ Missing: $file"
          else
            echo "✅ Found: $file"
          fi
        done
        
        if [ ${#missing_files[@]} -gt 0 ]; then
          echo ""
          echo "Error: Missing required files"
          exit 1
        fi
        
        echo ""
        echo "✅ All required files are present"
    
    - name: Check for trailing whitespace
      run: |
        echo "Checking for trailing whitespace in source files..."
        if grep -r --include='*.cpp' --include='*.h' ' $' .; then
          echo "⚠️  Warning: Found trailing whitespace (not blocking)"
        else
          echo "✅ No trailing whitespace found"
        fi
    
    - name: Verify file permissions
      run: |
        echo "Checking file permissions..."
        if [ -x "Makefile" ] || [ -x "CMakeLists.txt" ]; then
          echo "⚠️  Warning: Build files should not be executable"
        else
          echo "✅ File permissions look good"
        fi
    
    - name: Check for large files
      run: |
        echo "Checking for unexpectedly large files..."
        large_files=$(find . -type f -size +10M -not -path "./.git/*")
        if [ -n "$large_files" ]; then
          echo "⚠️  Warning: Found large files:"
          echo "$large_files"
        else
          echo "✅ No large files found"
        fi
    
    - name: Summary
      run: |
        echo ""
        echo "================================================"
        echo "✅ Code quality checks passed!"
        echo "================================================"
